# Generated by Django 5.1.7 on 2025-03-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('anonymous', 'Anonymous')], default='anonymous', max_length=10),
        ),
    ]
