# Generated by Django 5.1.7 on 2025-03-27 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='open_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='report.openspace'),
        ),
    ]
