# Generated by Django 5.1.7 on 2025-03-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openspace',
            old_name='longitude',
            new_name='longtude',
        ),
    ]
