# Generated by Django 5.1.7 on 2025-03-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_rename_longitude_openspace_longtude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reported_by',
            new_name='user',
        ),
    ]
