# Generated by Django 5.1.7 on 2025-03-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_rename_reported_by_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openspace',
            old_name='id',
            new_name='openspace_id',
        ),
    ]
